#define FLEX_COMPRESSED
/* A lexical scanner generated by flex */

/* scanner skeleton version:
 * $Header: flex.skel,v 2.0 89/06/20 15:49:46 vern Locked $
 */

#include <stdio.h>

#define FLEX_SCANNER

/* amount of stuff to slurp up with each read */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE (YY_READ_BUF_SIZE * 2) /* size of input buffer */
#endif

/* returned upon end-of-file */
#define YY_END_TOK 0

/* copy whatever the last rule matched to the standard output */

#define ECHO fputs( yytext, yyout )

/* gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#define YY_INPUT(buf,result,max_size) \
	if ( (result = read( fileno(yyin), buf, max_size )) < 0 ) \
	    YY_FATAL_ERROR( "read() in flex scanner failed" );
#define YY_NULL 0
#define yyterminate() return ( YY_NULL )

/* report a fatal error */
#define YY_FATAL_ERROR(msg) \
	{ \
	fputs( msg, stderr ); \
	putc( '\n', stderr ); \
	exit( 1 ); \
	}

/* default yywrap function - always treat EOF as an EOF */
#define yywrap() 1

/* enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN
 */
#define BEGIN yy_start = 1 + 2 *

/* action number for EOF rule of a given start state */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* special action meaning "start processing a new file" */
#define YY_NEW_FILE goto new_file

/* default declaration of generated scanner - a define so the user can
 * easily add parameters
 */
#define YY_DECL int yylex( void )

/* code executed at the end of each rule */
#define YY_BREAK break;

#define YY_END_OF_BUFFER_CHAR 0

/* done after the current pattern has been matched and before the
 * corresponding action - sets up yytext
 */
#define YY_DO_BEFORE_ACTION \
	yytext = yy_bp; \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

/* returns the length of the matched text */
#define yyleng (yy_cp - yy_bp)

#define EOB_ACT_RESTART_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* return all but the first 'n' matched characters back to the input stream */
#define yyless(n) \
	{ \
	*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
	yy_c_buf_p = yy_cp = yy_bp + n; \
	YY_DO_BEFORE_ACTION; /* set up yytext again */ \
	}

#define unput(c) yyunput( c, yy_bp )

#define YY_USER_ACTION

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
unsigned char  *yytext;

# line 1 "minic.l"
#define INITIAL 0
# line 2 "minic.l"
#include<stdio.h>
#include<math.h>
#include "d:\zbmprj\minic\misc.h"
#include "d:\zbmprj\minic\symbol.h"
#include "d:\zbmprj\minic\expr.h"
#include "d:\zbmprj\minic\term.h"

unsigned nLineNo = 1;
#define comment1 1
#define comment2 2
#define selfop 3
# line 20 "minic.l"
#define YY_END_OF_BUFFER 69
typedef int yy_state_type;
static const short int yy_accept[160] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   69,   57,
        3,    7,   41,   40,   57,   32,   38,   36,   31,   37,
       39,    4,   33,   35,   34,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   57,   58,
       59,   60,   61,   60,   67,   66,   65,   64,   63,    3,
       52,   48,   49,   46,   53,   44,   54,   45,    2,    1,
       47,    5,    4,   56,   56,   43,   51,   42,   55,   55,
       55,   11,   55,   55,   55,   55,    8,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       50,   62,   66,    5,    0,   56,    0,    6,   55,   26,

       55,   29,   55,    9,   55,   12,   55,   30,   55,   55,
       55,   55,   55,   25,   55,   27,   55,   55,   55,    6,
       55,   17,   55,   55,   55,   16,   55,   18,   55,   55,
       28,   14,   55,   55,   55,   13,   55,   55,   55,   55,
       55,   10,   19,   55,   55,   23,   22,   15,   55,   55,
       55,   55,   55,   55,   24,   55,   20,   21,    0
    } ;

static const unsigned char   yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    1,    1,    5,    6,    1,    7,
        7,    8,    9,   10,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,    1,    7,   15,
       16,   17,    1,    1,   18,   18,   18,   18,   19,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
        1,    1,    1,    1,   18,    1,   20,   18,   21,   22,

       23,   24,   25,   26,   27,   18,   18,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       18,   18,    7,   41,    7,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const char yy_meta[42] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    3,    1,    1,    1,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        1
    } ;

static const short int yy_base[166] =
    {   0,
        0,    0,  189,  188,   39,   40,   42,   47,  190,  193,
      187,  193,  172,  171,  180,  193,  169,   43,  193,   44,
       49,   49,  168,  167,  166,    0,   36,  150,   26,   42,
       45,   47,   51,  157,   53,  159,  147,   51,  136,  193,
      193,  193,  193,  163,  193,  173,  193,  193,  193,  172,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,   65,   75,    0,   81,  193,  193,  193,    0,  142,
      137,    0,  136,  138,  138,  134,    0,   64,  137,  141,
      138,  126,   61,  127,  132,  127,  130,  132,  131,  130,
      193,  193,  154,   82,   93,    0,  141,  140,  118,    0,

      129,    0,  131,    0,  114,    0,  126,    0,  118,  124,
      124,  108,  123,    0,  107,    0,  120,  113,  104,  125,
      115,    0,  101,  111,   99,    0,   98,    0,   99,  101,
        0,    0,  108,  107,  104,    0,   94,   96,   95,   95,
       96,    0,    0,   89,  102,    0,    0,    0,   90,  100,
       87,   72,   71,   73,    0,   67,    0,    0,  193,  107,
      110,  113,  115,   80,   43
    } ;

static const short int yy_def[166] =
    {   0,
      159,    1,  160,  160,  161,  161,  162,  162,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  163,  159,  159,  159,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  163,  165,  165,  159,  159,  159,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      159,  159,  159,  159,  159,  165,  159,  165,  164,  164,

      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  159,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,    0,  159,
      159,  159,  159,  159,  159
    } ;

static const short int yy_nxt[235] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   10,   21,   22,   23,   24,   25,   26,   26,   26,
       27,   28,   29,   30,   26,   26,   31,   32,   33,   26,
       26,   26,   26,   34,   35,   36,   26,   37,   38,   26,
       39,   43,   43,   46,   47,   96,   44,   44,   46,   47,
       48,   55,   49,   73,   57,   48,   59,   49,   56,   58,
       62,   60,   63,   70,   61,   74,   71,   65,   77,   75,
       81,   65,   76,   79,   78,   84,   89,   80,   94,   85,
      111,   82,   69,   95,   90,   86,   62,   95,   63,   97,
      105,   97,  158,   65,   98,   94,  112,   65,  157,  106,

       95,   97,  156,   97,   95,  155,  120,   40,   40,   40,
       42,   42,   42,   45,   45,   45,   64,   64,  154,  153,
      152,  151,  150,  149,  148,  147,  146,  145,  144,  143,
      142,  141,  140,  139,  138,  137,  136,  135,  120,  134,
      133,  132,  131,  130,  129,  128,  127,  126,  125,  124,
      123,  122,  121,   98,  120,   93,  119,  118,  117,  116,
      115,  114,  113,  110,  109,  108,  107,  104,  103,  102,
      101,  100,   99,   50,   93,   92,   91,   88,   87,   83,
       72,   68,   67,   66,   54,   53,   52,   51,   50,  159,
       41,   41,    9,  159,  159,  159,  159,  159,  159,  159,

      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159
    } ;

static const short int yy_chk[235] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    7,  165,    5,    6,    8,    8,
        7,   18,    7,   29,   20,    8,   21,    8,   18,   20,
       22,   21,   22,   27,   21,   29,   27,   22,   31,   30,
       33,   22,   30,   32,   31,   35,   38,   32,   62,   35,
       83,   33,  164,   62,   38,   35,   63,   62,   63,   65,
       78,   65,  156,   63,   65,   94,   83,   63,  154,   78,

       94,   95,  153,   95,   94,  152,   95,  160,  160,  160,
      161,  161,  161,  162,  162,  162,  163,  163,  151,  150,
      149,  145,  144,  141,  140,  139,  138,  137,  135,  134,
      133,  130,  129,  127,  125,  124,  123,  121,  120,  119,
      118,  117,  115,  113,  112,  111,  110,  109,  107,  105,
      103,  101,   99,   98,   97,   93,   90,   89,   88,   87,
       86,   85,   84,   82,   81,   80,   79,   76,   75,   74,
       73,   71,   70,   50,   46,   44,   39,   37,   36,   34,
       28,   25,   24,   23,   17,   15,   14,   13,   11,    9,
        4,    3,  159,  159,  159,  159,  159,  159,  159,  159,

      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159
    } ;

/* the intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected

/* these variables are all declared out here so that section 3 code can
 * manipulate them
 */
static unsigned char  *yy_c_buf_p;	/* points to current character in buffer */
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* true when we've seen an EOF for the current input file */
static int yy_eof_has_been_seen;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */

/* yy_ch_buf has to be 2 characters longer than YY_BUF_SIZE because we need
 * to put in 2 end-of-buffer characters (this is explained where it is
 * done) at the end of yy_ch_buf
 */
static unsigned char  yy_ch_buf[YY_BUF_SIZE + 2];

/* yy_hold_char holds the character lost when yytext is formed */
static unsigned char  yy_hold_char;

static yy_state_type yy_last_accepting_state;
static unsigned char  *yy_last_accepting_cpos;

static yy_state_type yy_get_previous_state( void );
static int yy_get_next_buffer( void );
static void yyunput( int c, unsigned char  *buf_ptr );
static int input( void );
static void yyrestart( FILE *input_file );

YY_DECL
    {
    register yy_state_type yy_current_state;
	register unsigned char  *yy_cp, *yy_bp;
    register int yy_act;




    if ( yy_init )
	{
	if ( ! yy_start )
	    yy_start = 1;	/* first start state */

	if ( ! yyin )
	    yyin = stdin;

	if ( ! yyout )
	    yyout = stdout;

new_file:
	/* this is where we enter upon encountering an end-of-file and
	 * yywrap() indicating that we should continue processing
	 */

	/* we put in the '\n' and start reading from [1] so that an
	 * initial match-at-newline will be true.
	 */

	yy_ch_buf[0] = '\n';
	yy_n_chars = 1;

	/* we always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yy_eof_has_been_seen = 0;

	yytext = yy_c_buf_p = &yy_ch_buf[1];
	yy_hold_char = *yy_c_buf_p;
	yy_init = 0;
	}

    while ( 1 )		/* loops until end-of-file is reached */
	{
	yy_cp = yy_c_buf_p;

	/* support of yytext */
	*yy_cp = yy_hold_char;

	/* yy_bp points to the position in yy_ch_buf of the start of the
	 * current run.
	 */
	yy_bp = yy_cp;

	yy_current_state = yy_start;
	do
	    {
	    register unsigned char   yy_c = yy_ec[*yy_cp];
	    if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = yy_def[yy_current_state];
		if ( yy_current_state >= 160 )
		    yy_c = yy_meta[yy_c];
		}
	    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	    ++yy_cp;
	    }
	while ( yy_current_state != 159 );
	yy_cp = yy_last_accepting_cpos;
	yy_current_state = yy_last_accepting_state;

	/* bogus while loop to let YY_BACK_TRACK, EOB_ACT_LAST_MATCH,
	 * and EOF actions branch here without introducing an optimizer-
	 * daunting goto
	 */
	while ( 1 )
	    {
	    yy_act = yy_accept[yy_current_state];

	    YY_DO_BEFORE_ACTION;
	    YY_USER_ACTION;

#ifdef FLEX_DEBUG
	    fprintf( stderr, "--accepting rule #%d (\"%s\")\n",
		     yy_act, yytext );
#endif

do_action:	/* this label is used only to access EOF actions */
	    switch ( yy_act )
		{
		case 0: /* must backtrack */
		/* undo the effects of YY_DO_BEFORE_ACTION */
		*yy_cp = yy_hold_char;
		yy_cp = yy_last_accepting_cpos;
		yy_current_state = yy_last_accepting_state;
		continue; /* go to "YY_DO_BEFORE_ACTION" */

case 1:
# line 22 "minic.l"
BEGIN comment1;
	YY_BREAK
case 2:
# line 23 "minic.l"
BEGIN comment2;
	YY_BREAK
case 3:
# line 24 "minic.l"
;
	YY_BREAK
case 4:
# line 25 "minic.l"
yylval.nValue = atoi(yytext); return INTEGER;
	YY_BREAK
case 5:
# line 26 "minic.l"
yylval.fValue = atof(yytext); return REAL;
	YY_BREAK
case 6:
# line 27 "minic.l"
yylval.fValue = atof(yytext); return REAL;
	YY_BREAK
case 7:
# line 28 "minic.l"
nLineNo++;
	YY_BREAK
case 8:
# line 29 "minic.l"
return IF;
	YY_BREAK
case 9:
# line 30 "minic.l"
return FOR;
	YY_BREAK
case 10:
# line 31 "minic.l"
return WHILE;
	YY_BREAK
case 11:
# line 32 "minic.l"
return DO;
	YY_BREAK
case 12:
# line 33 "minic.l"
return YTINT;
	YY_BREAK
case 13:
# line 34 "minic.l"
return YTFLOAT;
	YY_BREAK
case 14:
# line 35 "minic.l"
return YTVOID;
	YY_BREAK
case 15:
# line 36 "minic.l"
return RETURN;
	YY_BREAK
case 16:
# line 37 "minic.l"
return MAIN;
	YY_BREAK
case 17:
# line 38 "minic.l"
return ELSE;
	YY_BREAK
case 18:
# line 39 "minic.l"
return READ;
	YY_BREAK
case 19:
# line 40 "minic.l"
return WRITE;
	YY_BREAK
case 20:
# line 41 "minic.l"
return INITGRAPH;
	YY_BREAK
case 21:
# line 42 "minic.l"
return CLOSEGRAPH;
	YY_BREAK
case 22:
# line 43 "minic.l"
return MOVETO;
	YY_BREAK
case 23:
# line 44 "minic.l"
return LINETO;
	YY_BREAK
case 24:
# line 45 "minic.l"
return SETCOLOR;
	YY_BREAK
case 25:
# line 46 "minic.l"
yylval.opValue = ETSIN; 			return MATHFX;
	YY_BREAK
case 26:
# line 47 "minic.l"
yylval.opValue = ETCOS;			return MATHFX;
	YY_BREAK
case 27:
# line 48 "minic.l"
yylval.opValue = ETTAN;			return MATHFX;
	YY_BREAK
case 28:
# line 49 "minic.l"
yylval.opValue = ETSQRT;			return MATHFX;
	YY_BREAK
case 29:
# line 50 "minic.l"
yylval.opValue = ETEXP;			return MATHFX;
	YY_BREAK
case 30:
# line 51 "minic.l"
yylval.opValue = ETLOG;			return MATHFX;
	YY_BREAK
case 31:
# line 52 "minic.l"
yylval.opValue = ETCOMMA;		return COMMA;
	YY_BREAK
case 32:
# line 53 "minic.l"
return yytext[0];
	YY_BREAK
case 33:
# line 54 "minic.l"
yylval.opValue = ETSMALL; 		return COMPARE;
	YY_BREAK
case 34:
# line 55 "minic.l"
yylval.opValue = ETLARGE; 		return COMPARE;
	YY_BREAK
case 35:
# line 56 "minic.l"
yylval.opValue = ETASSIGN; 		return ASSIGN;
	YY_BREAK
case 36:
# line 57 "minic.l"
yylval.opValue = ETADD; 			return ADD;
	YY_BREAK
case 37:
# line 58 "minic.l"
yylval.opValue = ETSUB; 			return ADD;
	YY_BREAK
case 38:
# line 59 "minic.l"
yylval.opValue = ETMUL; 			return MUL;
	YY_BREAK
case 39:
# line 60 "minic.l"
yylval.opValue = ETDIV; 			return MUL;
	YY_BREAK
case 40:
# line 61 "minic.l"
yylval.opValue = ETMOD; 			return MUL;
	YY_BREAK
case 41:
# line 62 "minic.l"
yylval.opValue = ETNOT; 			return NOT;
	YY_BREAK
case 42:
# line 63 "minic.l"
yylval.opValue = ETLARGEEQU; 	return COMPARE;
	YY_BREAK
case 43:
# line 64 "minic.l"
yylval.opValue = ETSMALLEQU; 	return COMPARE;
	YY_BREAK
case 44:
# line 65 "minic.l"
yylval.opValue = ETADDASSIGN; 	return ASSIGN;
	YY_BREAK
case 45:
# line 66 "minic.l"
yylval.opValue = ETSUBASSIGN; 	return ASSIGN;
	YY_BREAK
case 46:
# line 67 "minic.l"
yylval.opValue = ETMULASSIGN; 	return ASSIGN;
	YY_BREAK
case 47:
# line 68 "minic.l"
yylval.opValue = ETDIVASSIGN; 	return ASSIGN;
	YY_BREAK
case 48:
# line 69 "minic.l"
yylval.opValue = ETMODASSIGN; 	return ASSIGN;
	YY_BREAK
case 49:
# line 70 "minic.l"
yylval.opValue = ETAND; 			return AND;
	YY_BREAK
case 50:
# line 71 "minic.l"
yylval.opValue = ETOR; 			return OR;
	YY_BREAK
case 51:
# line 72 "minic.l"
yylval.opValue = ETEQU; 			return EQU;
	YY_BREAK
case 52:
# line 73 "minic.l"
yylval.opValue = ETNOTEQU; 		return EQU;
	YY_BREAK
case 53:
# line 74 "minic.l"
yylval.opValue = ETINC; BEGIN selfop; return INC;
	YY_BREAK
case 54:
# line 75 "minic.l"
yylval.opValue = ETDEC; BEGIN selfop; return INC;
	YY_BREAK
case 55:
# line 76 "minic.l"
yylval.nValue = yyleng; return NAME;
	YY_BREAK
case 56:
# line 77 "minic.l"
return ERRTOKEN;
	YY_BREAK
case 57:
# line 78 "minic.l"
return ERRTOKEN;
	YY_BREAK
case 58:
# line 79 "minic.l"
;
	YY_BREAK
case 59:
# line 80 "minic.l"
BEGIN 0; nLineNo++;
	YY_BREAK
case 60:
# line 81 "minic.l"
;
	YY_BREAK
case 61:
# line 82 "minic.l"
nLineNo++;
	YY_BREAK
case 62:
# line 83 "minic.l"
BEGIN 0;
	YY_BREAK
case 63:
# line 84 "minic.l"
yylval.opValue = ETSUB; BEGIN 0; return ADD;	
	YY_BREAK
case 64:
# line 85 "minic.l"
yylval.opValue = ETADD; BEGIN 0; return ADD;
	YY_BREAK
case 65:
# line 86 "minic.l"
nLineNo++;
	YY_BREAK
case 66:
# line 87 "minic.l"
;
	YY_BREAK
case 67:
# line 88 "minic.l"
unput(yytext[0]); BEGIN 0;
	YY_BREAK
case 68:
# line 90 "minic.l"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment1):
case YY_STATE_EOF(comment2):
case YY_STATE_EOF(selfop):
    yyterminate();

		case YY_END_OF_BUFFER:
		    /* undo the effects of YY_DO_BEFORE_ACTION */
		    *yy_cp = yy_hold_char;

		    yytext = yy_bp;

		    switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
			    {
			    if ( yywrap() )
				{
				/* note: because we've taken care in
				 * yy_get_next_buffer() to have set up yytext,
				 * we can now set up yy_c_buf_p so that if some
				 * total hoser (like flex itself) wants
				 * to call the scanner after we return the
				 * YY_NULL, it'll still work - another YY_NULL
				 * will get returned.
				 */
				yy_c_buf_p = yytext;

				yy_act = YY_STATE_EOF((yy_start - 1) / 2);
				goto do_action;
				}

			    else
				YY_NEW_FILE;
			    }
			    break;

			case EOB_ACT_RESTART_SCAN:
			    yy_c_buf_p = yytext;
			    yy_hold_char = *yy_c_buf_p;
			    break;

			case EOB_ACT_LAST_MATCH:
			    yy_c_buf_p = &yy_ch_buf[yy_n_chars];

			    yy_current_state = yy_get_previous_state();

			    yy_cp = yy_c_buf_p;
			    yy_bp = yytext;
			    continue; /* go to "YY_DO_BEFORE_ACTION" */
			}
		    break;

		default:
		    printf( "action # %d\n", yy_act );
		    YY_FATAL_ERROR( "fatal flex scanner internal error" );
		}

	    break; /* exit bogus while loop */
	    }
	}
    }


/* yy_get_next_buffer - try to read in new buffer
 *
 * synopsis
 *     int yy_get_next_buffer();
 *
 * returns a code representing an action
 *     EOB_ACT_LAST_MATCH -
 *     EOB_ACT_RESTART_SCAN - restart the scanner
 *     EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()

    {
	register unsigned char  *dest = yy_ch_buf;
	register unsigned char  *source = yytext - 1; /* copy prev. char, too */
    register int number_to_move, i;
    int ret_val;

    if ( yy_c_buf_p != &yy_ch_buf[yy_n_chars + 1] )
	{
	YY_FATAL_ERROR( "NULL in input" );
	/*NOTREACHED*/
	}

    /* try to read more data */

    /* first move last chars to start of buffer */
    number_to_move = yy_c_buf_p - yytext;

    for ( i = 0; i < number_to_move; ++i )
	*(dest++) = *(source++);

    if ( yy_eof_has_been_seen )
	/* don't do the read, it's not guaranteed to return an EOF,
	 * just force an EOF
	 */
	yy_n_chars = 0;

    else
	{
	int num_to_read = YY_BUF_SIZE - number_to_move - 1;

	if ( num_to_read > YY_READ_BUF_SIZE )
	    num_to_read = YY_READ_BUF_SIZE;

	/* read in more data */
	YY_INPUT( (&yy_ch_buf[number_to_move]), yy_n_chars, num_to_read );
	}

    if ( yy_n_chars == 0 )
	{
	if ( number_to_move == 1 )
	    ret_val = EOB_ACT_END_OF_FILE;
	else
	    ret_val = EOB_ACT_LAST_MATCH;

	yy_eof_has_been_seen = 1;
	}

    else
	ret_val = EOB_ACT_RESTART_SCAN;

    yy_n_chars += number_to_move;
    yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    /* yytext begins at the second character in
     * yy_ch_buf; the first character is the one which
     * preceded it before reading in the latest buffer;
     * it needs to be kept around in case it's a
     * newline, so yy_get_previous_state() will have
     * with '^' rules active
     */

    yytext = &yy_ch_buf[1];

    return ( ret_val );
    }


/* yy_get_previous_state - get the state just before the EOB char was reached
 *
 * synopsis
 *     yy_state_type yy_get_previous_state();
 */

static yy_state_type yy_get_previous_state()

    {
    register yy_state_type yy_current_state;
	register unsigned char  *yy_cp;

    yy_current_state = yy_start;

    for ( yy_cp = yytext; yy_cp < yy_c_buf_p; ++yy_cp )
	{
	register unsigned char   yy_c = yy_ec[*yy_cp];
	if ( yy_accept[yy_current_state] )
	    {
	    yy_last_accepting_state = yy_current_state;
	    yy_last_accepting_cpos = yy_cp;
	    }
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	    {
	    yy_current_state = yy_def[yy_current_state];
	    if ( yy_current_state >= 160 )
		yy_c = yy_meta[yy_c];
	    }
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	}

    return ( yy_current_state );
    }


static void yyunput( int c, register unsigned char  *yy_bp )
    {
	register unsigned char  *yy_cp = yy_c_buf_p;

    *yy_cp = yy_hold_char; /* undo effects of setting up yytext */

    if ( yy_cp < yy_ch_buf + 2 )
	{ /* need to shift things up to make room */
	register int number_to_move = yy_n_chars + 2; /* +2 for EOB chars */
	register unsigned char  *dest = &yy_ch_buf[YY_BUF_SIZE + 2];
	register unsigned char  *source = &yy_ch_buf[number_to_move];

	while ( source > yy_ch_buf )
	    *--dest = *--source;

	yy_cp += dest - source;
	yy_bp += dest - source;

	if ( yy_cp < yy_ch_buf + 2 )
	    YY_FATAL_ERROR( "flex scanner push-back overflow" );
	}

    if ( yy_cp > yy_bp && yy_cp[-1] == '\n' )
	yy_cp[-2] = '\n';

    *--yy_cp = c;

    YY_DO_BEFORE_ACTION; /* set up yytext again */
    }


static int input()

    {
    int c;
	unsigned char  *yy_cp = yy_c_buf_p;

    *yy_cp = yy_hold_char;

    if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
	{ /* need more input */
	yytext = yy_c_buf_p;
	++yy_c_buf_p;

	switch ( yy_get_next_buffer() )
	    {
	    /* this code, unfortunately, is somewhat redundant with
	     * that above
	     */
	    case EOB_ACT_END_OF_FILE:
		{
		if ( yywrap() )
		    {
		    yy_c_buf_p = yytext;
		    return ( EOF );
		    }

		yy_ch_buf[0] = '\n';
		yy_n_chars = 1;
		yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
		yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;
		yy_eof_has_been_seen = 0;
		yytext = yy_c_buf_p = &yy_ch_buf[1];
		yy_hold_char = *yy_c_buf_p;

		return ( input() );
		}
		break;

	    case EOB_ACT_RESTART_SCAN:
		yy_c_buf_p = yytext;
		break;

	    case EOB_ACT_LAST_MATCH:
		YY_FATAL_ERROR( "unexpected last match in input()" );
	    }
	}

    c = *yy_c_buf_p;
    yy_hold_char = *++yy_c_buf_p;

    return ( c );
    }


static void yyrestart( FILE *input_file )
    {
    if ( yyin != stdin )
	fclose( yyin );

    yyin = input_file;
    yy_init = 1;
    }
# line 90 "minic.l"


void ScannerRestart(FILE* fp)
{
	if(fp==NULL)
	{
    	if ( yyin != stdin )
		{
			fclose( yyin );
			yyrestart( stdin );
		}
		return;
	}
	yyrestart(fp);
}