//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WinWq.rc
//
#define IDD_ABOUTBOX                    100
#define IDS_PROPSHT_CAPTION             102
#define IDD_SETTINGDLG                  103
#define IDB_LIGHTBULB                   105
#define IDD_TIP                         106
#define CG_IDS_TIPOFTHEDAY              107
#define CG_IDS_TIPOFTHEDAYMENU          108
#define CG_IDS_DIDYOUKNOW               109
#define CG_IDS_FILE_ABSENT              110
#define CG_IDP_FILE_CORRUPT             111
#define CG_IDS_TIPOFTHEDAYHELP          112
#define IDC_STAT_LIST                   113
#define IDR_MAINFRAME                   128
#define IDR_WINWQTYPE                   129
#define IDD_INFORMATION                 130
#define IDB_BOARD                       133
#define IDC_WHITE                       134
#define IDC_BLACK                       136
#define IDB_BLACK                       139
#define IDB_WHITE                       140
#define IDD_NEWGAME                     141
#define IDR_BWMENU                      143
#define IDD_MULTI_REGRET                150
#define IDD_ENDGAME                     151
#define IDD_FINDPIECE                   152
#define IDD_ATTRIB                      155
#define IDD_WQ_OPENDLG                  166
#define IDC_BULB                        1000
#define IDC_STARTUP                     1001
#define IDC_NEXTTIP                     1002
#define IDC_TIPSTRING                   1004
#define IDC_GAMEDATE                    1007
#define IDC_GAME_NAME                   1008
#define IDC_BLACK_NAME                  1009
#define IDC_WHITE_NAME                  1010
#define IDC_BLACK_DEGREE                1011
#define IDC_WHITE_DEGREE                1012
#define IDC_FREE                        1013
#define IDC_STARDARD                    1014
#define IDC_FASTGAME                    1015
#define IDC_RECORD                      1016
#define IDC_BLACK_PREPUT                1018
#define IDC_DISCRIBE                    1020
#define IDC_PUT_BLACK                   1023
#define IDC_PUT_WHITE                   1024
#define IDC_TOTAL_IN_GAME               1045
#define IDC_CURRENT_IN_GAME             1046
#define IDC_EDIT_HAND                   1047
#define IDC_SPIN1                       1048
#define IDC_WINLOST                     1049
#define IDC_MIDDLEGAME                  1050
#define IDC_GUANZI                      1051
#define IDC_SPIN2                       1052
#define IDC_BLACK_TIMEUSED              1053
#define IDC_WHITE_TIMEUSED              1054
#define IDC_MAXHAND                     1055
#define IDC_PIECE_TO_FIND               1056
#define IDC_MAXKILLS                    1056
#define IDC_BOARD_PANES                 1057
#define IDC_CONTEXT_MENU                1058
#define IDC_MUSIC_FILE_NAME             1059
#define IDC_BTN_MUSIC_FILE              1060
#define IDC_GIVE_ANSWER                 1061
#define IDC_RADIO2                      1062
#define IDC_PREPUT_NUM_INGUESS          1063
#define IDC_AUTOREPLAY_DELAY_TIME       1064
#define IDC_MAXBLOCK                    1065
#define IDC_ALLOW_OVERTIME              1067
#define IDC_SPIN4                       1069
#define IDC_ALLOW_OVERTIME_FAST         1070
#define IDC_SPIN5                       1071
#define IDC_ENTIRE_GAME_TIME            1074
#define IDC_SPIN_ENTIRE_GAME            1075
#define IDC_ENTIRE_GAME_TIME2           1076
#define IDC_SPIN_ENTIRE_GAME2           1077
#define IDC_EDIT_COMMENT                1078
#define IDC_MIDDLE                      1082
#define IDC_GAMEDISCRIBE                1090
#define IDC_PIECEDISCRIBE               1091
#define IDC_SPINMAXHAND                 1093
#define IDC_SPINMAXKILLS                1094
#define IDC_SPINMAXBLOCK                1095
#define IDC_DEFAULT                     1096
#define IDC_INVERT_COLOR                1125
#define IDC_DELETE                      1126
#define IDC_CURRENT_POSITION            1127
#define IDC_REGRET_TO_START             1128
#define IDC_REGRET                      1129
#define IDC_CURRENT_SERNUM              1130
#define IDC_REPUT                       1131
#define IDC_REPUT_TO_END                1132
#define IDC_GIVE_IN                     1133
#define IDC_GIVE_UP                     1134
#define IDC_BLACK_KILLS                 1135
#define IDC_WHITE_KILLS                 1136
#define IDC_BLACK_TIME                  1137
#define IDC_WHITE_TIME                  1138
#define IDC_GAMENAME                    1139
#define IDC_BLACKNAME                   1140
#define IDC_WHITENAME                   1141
#define IDC_BUTTON1                     1142
#define ID_EDIT_REGRET                  32771
#define ID_EDIT_REGRET_MORE             32772
#define ID_EDIT_DELETE                  32773
#define ID_PUT_BLACK                    32774
#define ID_PUT_WHITE                    32775
#define ID_EDIT_INVERT                  32776
#define ID_OPTION_MUSIC                 32777
#define ID_OPTION_SOUND                 32778
#define ID_OPTION_SETTINGS              32779
#define ID_SHOW_ORDER                   32780
#define ID_PROPERTIES                   32782
#define ID_CANCEL                       32783
#define ID_EDIT_REPUT                   32784
#define ID_REPLAY                       32785
#define ID_AUTO_REPLAY                  32786
#define ID_GUESS                        32787
#define ID_MOVIFY                       32788
#define ID_GIVE_IN                      32789
#define ID_EDIT_LOST                    32790
#define ID_FIND_PIECE                   32791
#define ID_TIP_OF_DAY                   32792
#define ID_CONVERT                      32793
#define IDS_NO_DIRECTSOUND              61444

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        171
#define _APS_NEXT_COMMAND_VALUE         32794
#define _APS_NEXT_CONTROL_VALUE         1098
#define _APS_NEXT_SYMED_VALUE           114
#endif
#endif
