//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace WedDress {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("RentDetail")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class RentDetail : global::System.Data.DataSet {
        
        private RentDetailDataTable tableRentDetail;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public RentDetail() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected RentDetail(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["RentDetail"] != null)) {
                    base.Tables.Add(new RentDetailDataTable(ds.Tables["RentDetail"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public RentDetailDataTable _RentDetail {
            get {
                return this.tableRentDetail;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            RentDetail cln = ((RentDetail)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["RentDetail"] != null)) {
                    base.Tables.Add(new RentDetailDataTable(ds.Tables["RentDetail"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableRentDetail = ((RentDetailDataTable)(base.Tables["RentDetail"]));
            if ((initTable == true)) {
                if ((this.tableRentDetail != null)) {
                    this.tableRentDetail.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "RentDetail";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/RentDetail.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableRentDetail = new RentDetailDataTable();
            base.Tables.Add(this.tableRentDetail);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerialize_RentDetail() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            RentDetail ds = new RentDetail();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void RentDetailRowChangeEventHandler(object sender, RentDetailRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class RentDetailDataTable : global::System.Data.DataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columnYearMonth;
            
            private global::System.Data.DataColumn columnd01;
            
            private global::System.Data.DataColumn columnd02;
            
            private global::System.Data.DataColumn columnd03;
            
            private global::System.Data.DataColumn columnd04;
            
            private global::System.Data.DataColumn columnd05;
            
            private global::System.Data.DataColumn columnd06;
            
            private global::System.Data.DataColumn columnd07;
            
            private global::System.Data.DataColumn columnd08;
            
            private global::System.Data.DataColumn columnd09;
            
            private global::System.Data.DataColumn columnd10;
            
            private global::System.Data.DataColumn columnd11;
            
            private global::System.Data.DataColumn columnd12;
            
            private global::System.Data.DataColumn columnd13;
            
            private global::System.Data.DataColumn columnd14;
            
            private global::System.Data.DataColumn columnd15;
            
            private global::System.Data.DataColumn columnd16;
            
            private global::System.Data.DataColumn columnd17;
            
            private global::System.Data.DataColumn columnd18;
            
            private global::System.Data.DataColumn columnd19;
            
            private global::System.Data.DataColumn columnd20;
            
            private global::System.Data.DataColumn columnd21;
            
            private global::System.Data.DataColumn columnd22;
            
            private global::System.Data.DataColumn columnd23;
            
            private global::System.Data.DataColumn columnd24;
            
            private global::System.Data.DataColumn columnd25;
            
            private global::System.Data.DataColumn columnd26;
            
            private global::System.Data.DataColumn columnd27;
            
            private global::System.Data.DataColumn columnd28;
            
            private global::System.Data.DataColumn columnd29;
            
            private global::System.Data.DataColumn columnd30;
            
            private global::System.Data.DataColumn columnd31;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public RentDetailDataTable() {
                this.TableName = "RentDetail";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal RentDetailDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected RentDetailDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn YearMonthColumn {
                get {
                    return this.columnYearMonth;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn d01Column {
                get {
                    return this.columnd01;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn d02Column {
                get {
                    return this.columnd02;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn d03Column {
                get {
                    return this.columnd03;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn d04Column {
                get {
                    return this.columnd04;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn d05Column {
                get {
                    return this.columnd05;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn d06Column {
                get {
                    return this.columnd06;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn d07Column {
                get {
                    return this.columnd07;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn d08Column {
                get {
                    return this.columnd08;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn d09Column {
                get {
                    return this.columnd09;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn d10Column {
                get {
                    return this.columnd10;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn d11Column {
                get {
                    return this.columnd11;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn d12Column {
                get {
                    return this.columnd12;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn d13Column {
                get {
                    return this.columnd13;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn d14Column {
                get {
                    return this.columnd14;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn d15Column {
                get {
                    return this.columnd15;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn d16Column {
                get {
                    return this.columnd16;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn d17Column {
                get {
                    return this.columnd17;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn d18Column {
                get {
                    return this.columnd18;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn d19Column {
                get {
                    return this.columnd19;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn d20Column {
                get {
                    return this.columnd20;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn d21Column {
                get {
                    return this.columnd21;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn d22Column {
                get {
                    return this.columnd22;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn d23Column {
                get {
                    return this.columnd23;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn d24Column {
                get {
                    return this.columnd24;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn d25Column {
                get {
                    return this.columnd25;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn d26Column {
                get {
                    return this.columnd26;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn d27Column {
                get {
                    return this.columnd27;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn d28Column {
                get {
                    return this.columnd28;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn d29Column {
                get {
                    return this.columnd29;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn d30Column {
                get {
                    return this.columnd30;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn d31Column {
                get {
                    return this.columnd31;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public RentDetailRow this[int index] {
                get {
                    return ((RentDetailRow)(this.Rows[index]));
                }
            }
            
            public event RentDetailRowChangeEventHandler RentDetailRowChanging;
            
            public event RentDetailRowChangeEventHandler RentDetailRowChanged;
            
            public event RentDetailRowChangeEventHandler RentDetailRowDeleting;
            
            public event RentDetailRowChangeEventHandler RentDetailRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddRentDetailRow(RentDetailRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public RentDetailRow AddRentDetailRow(
                        System.DateTime YearMonth, 
                        string d01, 
                        string d02, 
                        string d03, 
                        string d04, 
                        string d05, 
                        string d06, 
                        string d07, 
                        string d08, 
                        string d09, 
                        string d10, 
                        string d11, 
                        string d12, 
                        string d13, 
                        string d14, 
                        string d15, 
                        string d16, 
                        string d17, 
                        string d18, 
                        string d19, 
                        string d20, 
                        string d21, 
                        string d22, 
                        string d23, 
                        string d24, 
                        string d25, 
                        string d26, 
                        string d27, 
                        string d28, 
                        string d29, 
                        string d30, 
                        string d31) {
                RentDetailRow rowRentDetailRow = ((RentDetailRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        YearMonth,
                        d01,
                        d02,
                        d03,
                        d04,
                        d05,
                        d06,
                        d07,
                        d08,
                        d09,
                        d10,
                        d11,
                        d12,
                        d13,
                        d14,
                        d15,
                        d16,
                        d17,
                        d18,
                        d19,
                        d20,
                        d21,
                        d22,
                        d23,
                        d24,
                        d25,
                        d26,
                        d27,
                        d28,
                        d29,
                        d30,
                        d31};
                rowRentDetailRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowRentDetailRow);
                return rowRentDetailRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                RentDetailDataTable cln = ((RentDetailDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new RentDetailDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnYearMonth = base.Columns["YearMonth"];
                this.columnd01 = base.Columns["d01"];
                this.columnd02 = base.Columns["d02"];
                this.columnd03 = base.Columns["d03"];
                this.columnd04 = base.Columns["d04"];
                this.columnd05 = base.Columns["d05"];
                this.columnd06 = base.Columns["d06"];
                this.columnd07 = base.Columns["d07"];
                this.columnd08 = base.Columns["d08"];
                this.columnd09 = base.Columns["d09"];
                this.columnd10 = base.Columns["d10"];
                this.columnd11 = base.Columns["d11"];
                this.columnd12 = base.Columns["d12"];
                this.columnd13 = base.Columns["d13"];
                this.columnd14 = base.Columns["d14"];
                this.columnd15 = base.Columns["d15"];
                this.columnd16 = base.Columns["d16"];
                this.columnd17 = base.Columns["d17"];
                this.columnd18 = base.Columns["d18"];
                this.columnd19 = base.Columns["d19"];
                this.columnd20 = base.Columns["d20"];
                this.columnd21 = base.Columns["d21"];
                this.columnd22 = base.Columns["d22"];
                this.columnd23 = base.Columns["d23"];
                this.columnd24 = base.Columns["d24"];
                this.columnd25 = base.Columns["d25"];
                this.columnd26 = base.Columns["d26"];
                this.columnd27 = base.Columns["d27"];
                this.columnd28 = base.Columns["d28"];
                this.columnd29 = base.Columns["d29"];
                this.columnd30 = base.Columns["d30"];
                this.columnd31 = base.Columns["d31"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnYearMonth = new global::System.Data.DataColumn("YearMonth", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnYearMonth);
                this.columnd01 = new global::System.Data.DataColumn("d01", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnd01);
                this.columnd02 = new global::System.Data.DataColumn("d02", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnd02);
                this.columnd03 = new global::System.Data.DataColumn("d03", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnd03);
                this.columnd04 = new global::System.Data.DataColumn("d04", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnd04);
                this.columnd05 = new global::System.Data.DataColumn("d05", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnd05);
                this.columnd06 = new global::System.Data.DataColumn("d06", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnd06);
                this.columnd07 = new global::System.Data.DataColumn("d07", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnd07);
                this.columnd08 = new global::System.Data.DataColumn("d08", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnd08);
                this.columnd09 = new global::System.Data.DataColumn("d09", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnd09);
                this.columnd10 = new global::System.Data.DataColumn("d10", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnd10);
                this.columnd11 = new global::System.Data.DataColumn("d11", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnd11);
                this.columnd12 = new global::System.Data.DataColumn("d12", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnd12);
                this.columnd13 = new global::System.Data.DataColumn("d13", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnd13);
                this.columnd14 = new global::System.Data.DataColumn("d14", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnd14);
                this.columnd15 = new global::System.Data.DataColumn("d15", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnd15);
                this.columnd16 = new global::System.Data.DataColumn("d16", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnd16);
                this.columnd17 = new global::System.Data.DataColumn("d17", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnd17);
                this.columnd18 = new global::System.Data.DataColumn("d18", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnd18);
                this.columnd19 = new global::System.Data.DataColumn("d19", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnd19);
                this.columnd20 = new global::System.Data.DataColumn("d20", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnd20);
                this.columnd21 = new global::System.Data.DataColumn("d21", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnd21);
                this.columnd22 = new global::System.Data.DataColumn("d22", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnd22);
                this.columnd23 = new global::System.Data.DataColumn("d23", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnd23);
                this.columnd24 = new global::System.Data.DataColumn("d24", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnd24);
                this.columnd25 = new global::System.Data.DataColumn("d25", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnd25);
                this.columnd26 = new global::System.Data.DataColumn("d26", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnd26);
                this.columnd27 = new global::System.Data.DataColumn("d27", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnd27);
                this.columnd28 = new global::System.Data.DataColumn("d28", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnd28);
                this.columnd29 = new global::System.Data.DataColumn("d29", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnd29);
                this.columnd30 = new global::System.Data.DataColumn("d30", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnd30);
                this.columnd31 = new global::System.Data.DataColumn("d31", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnd31);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("Constraint1", new global::System.Data.DataColumn[] {
                                this.columnYearMonth}, false));
                this.columnYearMonth.AllowDBNull = false;
                this.columnYearMonth.Unique = true;
                this.ExtendedProperties.Add("Generator_TablePropName", "_RentDetail");
                this.ExtendedProperties.Add("Generator_UserTableName", "RentDetail");
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public RentDetailRow NewRentDetailRow() {
                return ((RentDetailRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new RentDetailRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(RentDetailRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.RentDetailRowChanged != null)) {
                    this.RentDetailRowChanged(this, new RentDetailRowChangeEvent(((RentDetailRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.RentDetailRowChanging != null)) {
                    this.RentDetailRowChanging(this, new RentDetailRowChangeEvent(((RentDetailRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.RentDetailRowDeleted != null)) {
                    this.RentDetailRowDeleted(this, new RentDetailRowChangeEvent(((RentDetailRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.RentDetailRowDeleting != null)) {
                    this.RentDetailRowDeleting(this, new RentDetailRowChangeEvent(((RentDetailRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveRentDetailRow(RentDetailRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                RentDetail ds = new RentDetail();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "RentDetailDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class RentDetailRow : global::System.Data.DataRow {
            
            private RentDetailDataTable tableRentDetail;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal RentDetailRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableRentDetail = ((RentDetailDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime YearMonth {
                get {
                    return ((global::System.DateTime)(this[this.tableRentDetail.YearMonthColumn]));
                }
                set {
                    this[this.tableRentDetail.YearMonthColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string d01 {
                get {
                    try {
                        return ((string)(this[this.tableRentDetail.d01Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'d01\' in table \'RentDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRentDetail.d01Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string d02 {
                get {
                    try {
                        return ((string)(this[this.tableRentDetail.d02Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'d02\' in table \'RentDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRentDetail.d02Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string d03 {
                get {
                    try {
                        return ((string)(this[this.tableRentDetail.d03Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'d03\' in table \'RentDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRentDetail.d03Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string d04 {
                get {
                    try {
                        return ((string)(this[this.tableRentDetail.d04Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'d04\' in table \'RentDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRentDetail.d04Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string d05 {
                get {
                    try {
                        return ((string)(this[this.tableRentDetail.d05Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'d05\' in table \'RentDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRentDetail.d05Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string d06 {
                get {
                    try {
                        return ((string)(this[this.tableRentDetail.d06Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'d06\' in table \'RentDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRentDetail.d06Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string d07 {
                get {
                    try {
                        return ((string)(this[this.tableRentDetail.d07Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'d07\' in table \'RentDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRentDetail.d07Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string d08 {
                get {
                    try {
                        return ((string)(this[this.tableRentDetail.d08Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'d08\' in table \'RentDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRentDetail.d08Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string d09 {
                get {
                    try {
                        return ((string)(this[this.tableRentDetail.d09Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'d09\' in table \'RentDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRentDetail.d09Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string d10 {
                get {
                    try {
                        return ((string)(this[this.tableRentDetail.d10Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'d10\' in table \'RentDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRentDetail.d10Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string d11 {
                get {
                    try {
                        return ((string)(this[this.tableRentDetail.d11Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'d11\' in table \'RentDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRentDetail.d11Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string d12 {
                get {
                    try {
                        return ((string)(this[this.tableRentDetail.d12Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'d12\' in table \'RentDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRentDetail.d12Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string d13 {
                get {
                    try {
                        return ((string)(this[this.tableRentDetail.d13Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'d13\' in table \'RentDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRentDetail.d13Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string d14 {
                get {
                    try {
                        return ((string)(this[this.tableRentDetail.d14Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'d14\' in table \'RentDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRentDetail.d14Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string d15 {
                get {
                    try {
                        return ((string)(this[this.tableRentDetail.d15Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'d15\' in table \'RentDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRentDetail.d15Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string d16 {
                get {
                    try {
                        return ((string)(this[this.tableRentDetail.d16Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'d16\' in table \'RentDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRentDetail.d16Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string d17 {
                get {
                    try {
                        return ((string)(this[this.tableRentDetail.d17Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'d17\' in table \'RentDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRentDetail.d17Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string d18 {
                get {
                    try {
                        return ((string)(this[this.tableRentDetail.d18Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'d18\' in table \'RentDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRentDetail.d18Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string d19 {
                get {
                    try {
                        return ((string)(this[this.tableRentDetail.d19Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'d19\' in table \'RentDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRentDetail.d19Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string d20 {
                get {
                    try {
                        return ((string)(this[this.tableRentDetail.d20Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'d20\' in table \'RentDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRentDetail.d20Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string d21 {
                get {
                    try {
                        return ((string)(this[this.tableRentDetail.d21Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'d21\' in table \'RentDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRentDetail.d21Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string d22 {
                get {
                    try {
                        return ((string)(this[this.tableRentDetail.d22Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'d22\' in table \'RentDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRentDetail.d22Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string d23 {
                get {
                    try {
                        return ((string)(this[this.tableRentDetail.d23Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'d23\' in table \'RentDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRentDetail.d23Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string d24 {
                get {
                    try {
                        return ((string)(this[this.tableRentDetail.d24Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'d24\' in table \'RentDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRentDetail.d24Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string d25 {
                get {
                    try {
                        return ((string)(this[this.tableRentDetail.d25Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'d25\' in table \'RentDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRentDetail.d25Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string d26 {
                get {
                    try {
                        return ((string)(this[this.tableRentDetail.d26Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'d26\' in table \'RentDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRentDetail.d26Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string d27 {
                get {
                    try {
                        return ((string)(this[this.tableRentDetail.d27Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'d27\' in table \'RentDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRentDetail.d27Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string d28 {
                get {
                    try {
                        return ((string)(this[this.tableRentDetail.d28Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'d28\' in table \'RentDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRentDetail.d28Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string d29 {
                get {
                    try {
                        return ((string)(this[this.tableRentDetail.d29Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'d29\' in table \'RentDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRentDetail.d29Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string d30 {
                get {
                    try {
                        return ((string)(this[this.tableRentDetail.d30Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'d30\' in table \'RentDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRentDetail.d30Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string d31 {
                get {
                    try {
                        return ((string)(this[this.tableRentDetail.d31Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'d31\' in table \'RentDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRentDetail.d31Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isd01Null() {
                return this.IsNull(this.tableRentDetail.d01Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setd01Null() {
                this[this.tableRentDetail.d01Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isd02Null() {
                return this.IsNull(this.tableRentDetail.d02Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setd02Null() {
                this[this.tableRentDetail.d02Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isd03Null() {
                return this.IsNull(this.tableRentDetail.d03Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setd03Null() {
                this[this.tableRentDetail.d03Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isd04Null() {
                return this.IsNull(this.tableRentDetail.d04Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setd04Null() {
                this[this.tableRentDetail.d04Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isd05Null() {
                return this.IsNull(this.tableRentDetail.d05Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setd05Null() {
                this[this.tableRentDetail.d05Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isd06Null() {
                return this.IsNull(this.tableRentDetail.d06Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setd06Null() {
                this[this.tableRentDetail.d06Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isd07Null() {
                return this.IsNull(this.tableRentDetail.d07Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setd07Null() {
                this[this.tableRentDetail.d07Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isd08Null() {
                return this.IsNull(this.tableRentDetail.d08Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setd08Null() {
                this[this.tableRentDetail.d08Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isd09Null() {
                return this.IsNull(this.tableRentDetail.d09Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setd09Null() {
                this[this.tableRentDetail.d09Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isd10Null() {
                return this.IsNull(this.tableRentDetail.d10Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setd10Null() {
                this[this.tableRentDetail.d10Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isd11Null() {
                return this.IsNull(this.tableRentDetail.d11Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setd11Null() {
                this[this.tableRentDetail.d11Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isd12Null() {
                return this.IsNull(this.tableRentDetail.d12Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setd12Null() {
                this[this.tableRentDetail.d12Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isd13Null() {
                return this.IsNull(this.tableRentDetail.d13Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setd13Null() {
                this[this.tableRentDetail.d13Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isd14Null() {
                return this.IsNull(this.tableRentDetail.d14Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setd14Null() {
                this[this.tableRentDetail.d14Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isd15Null() {
                return this.IsNull(this.tableRentDetail.d15Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setd15Null() {
                this[this.tableRentDetail.d15Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isd16Null() {
                return this.IsNull(this.tableRentDetail.d16Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setd16Null() {
                this[this.tableRentDetail.d16Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isd17Null() {
                return this.IsNull(this.tableRentDetail.d17Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setd17Null() {
                this[this.tableRentDetail.d17Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isd18Null() {
                return this.IsNull(this.tableRentDetail.d18Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setd18Null() {
                this[this.tableRentDetail.d18Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isd19Null() {
                return this.IsNull(this.tableRentDetail.d19Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setd19Null() {
                this[this.tableRentDetail.d19Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isd20Null() {
                return this.IsNull(this.tableRentDetail.d20Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setd20Null() {
                this[this.tableRentDetail.d20Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isd21Null() {
                return this.IsNull(this.tableRentDetail.d21Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setd21Null() {
                this[this.tableRentDetail.d21Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isd22Null() {
                return this.IsNull(this.tableRentDetail.d22Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setd22Null() {
                this[this.tableRentDetail.d22Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isd23Null() {
                return this.IsNull(this.tableRentDetail.d23Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setd23Null() {
                this[this.tableRentDetail.d23Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isd24Null() {
                return this.IsNull(this.tableRentDetail.d24Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setd24Null() {
                this[this.tableRentDetail.d24Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isd25Null() {
                return this.IsNull(this.tableRentDetail.d25Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setd25Null() {
                this[this.tableRentDetail.d25Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isd26Null() {
                return this.IsNull(this.tableRentDetail.d26Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setd26Null() {
                this[this.tableRentDetail.d26Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isd27Null() {
                return this.IsNull(this.tableRentDetail.d27Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setd27Null() {
                this[this.tableRentDetail.d27Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isd28Null() {
                return this.IsNull(this.tableRentDetail.d28Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setd28Null() {
                this[this.tableRentDetail.d28Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isd29Null() {
                return this.IsNull(this.tableRentDetail.d29Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setd29Null() {
                this[this.tableRentDetail.d29Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isd30Null() {
                return this.IsNull(this.tableRentDetail.d30Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setd30Null() {
                this[this.tableRentDetail.d30Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isd31Null() {
                return this.IsNull(this.tableRentDetail.d31Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setd31Null() {
                this[this.tableRentDetail.d31Column] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class RentDetailRowChangeEvent : global::System.EventArgs {
            
            private RentDetailRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public RentDetailRowChangeEvent(RentDetailRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public RentDetailRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591